// Central theme registry for Nest Finance.
// Each entry defines the design tokens that feed both Tailwind and custom CSS.
// To add a new theme, append a new key to `themes` with matching `colors`, `typography`, and `ui` objects.
// Every `colors` property maps to a CSS variable named `--color-<token>` (camelCase → kebab-case).
// Typography values populate `--font-*` variables and `ui` values populate `--border-radius-*` (plus any extra ui tokens).

const themes = {
  default: {
    label: 'Default',
    colors: {
      background: '#f8fafc',
      surface: '#ffffff',
      surfaceMuted: '#f1f5f9',
      surfaceElevated: '#ffffff',
      border: '#e2e8f0',
      ring: '#10b981',
      primary: '#0f766e',
      primarySoft: '#14b8a6',
      primaryContent: '#ffffff',
      secondary: '#1d4ed8',
      secondaryContent: '#ffffff',
      accent: '#f97316',
      accentContent: '#0f172a',
      textPrimary: '#0f172a',
      textSecondary: '#334155',
      textMuted: '#64748b',
      success: '#16a34a',
      warning: '#f59e0b',
      destructive: '#dc2626',
      destructiveContent: '#ffffff',
    },
    typography: {
      fontFamilySans: "'Inter', sans-serif",
      fontFamilyDisplay: "'Sora', sans-serif",
      baseFontSize: '16px',
      fontWeightLight: '300',
      fontWeightRegular: '400',
      fontWeightBold: '600',
    },
    ui: {
      borderRadiusSmall: '0.375rem',
      borderRadiusMedium: '0.75rem',
      borderRadiusLarge: '1.25rem',
      borderRadiusPill: '9999px',
      shadowSoft: '0 10px 15px -3px rgba(15, 23, 42, 0.12), 0 4px 6px -4px rgba(15, 23, 42, 0.08)',
    },
  },
  elegant: {
    label: 'Elegant',
    colors: {
      background: '#fdfbf7',
      surface: '#ffffff',
      surfaceMuted: '#f9f6f2',
      surfaceElevated: '#f4ece2',
      border: '#ede7e0',
      ring: '#c08a3e',
      primary: '#8c5a32',
      primarySoft: '#a47246',
      primaryContent: '#fdfbf7',
      secondary: '#5a3d2b',
      secondaryContent: '#fdfbf7',
      accent: '#c08a3e',
      accentContent: '#2d2a26',
      textPrimary: '#2d2a26',
      textSecondary: '#5a534e',
      textMuted: '#8b827b',
      success: '#2f855a',
      warning: '#d97706',
      destructive: '#b91c1c',
      destructiveContent: '#fdfbf7',
    },
    typography: {
      fontFamilySans: "'Lora', serif",
      fontFamilyDisplay: "'Playfair Display', serif",
      baseFontSize: '17px',
      fontWeightLight: '300',
      fontWeightRegular: '400',
      fontWeightBold: '700',
    },
    ui: {
      borderRadiusSmall: '0.25rem',
      borderRadiusMedium: '0.5rem',
      borderRadiusLarge: '1rem',
      borderRadiusPill: '9999px',
      shadowSoft: '0 12px 24px -10px rgba(44, 30, 15, 0.35)',
    },
  },
  techno: {
    label: 'Techno',
    colors: {
      background: '#0a0c1f',
      surface: '#111528',
      surfaceMuted: '#1a1f3a',
      surfaceElevated: '#1f2642',
      border: '#2c3454',
      ring: '#00f6ff',
      primary: '#00f6ff',
      primarySoft: '#7dffff',
      primaryContent: '#0a0c1f',
      secondary: '#ff3dff',
      secondaryContent: '#0a0c1f',
      accent: '#7c3aed',
      accentContent: '#0a0c1f',
      textPrimary: '#e0e8ff',
      textSecondary: '#a0b3d8',
      textMuted: '#6b7b9c',
      success: '#22d3ee',
      warning: '#facc15',
      destructive: '#f43f5e',
      destructiveContent: '#0a0c1f',
    },
    typography: {
      fontFamilySans: "'Space Grotesk', sans-serif",
      fontFamilyDisplay: "'VT323', monospace",
      baseFontSize: '15px',
      fontWeightLight: '300',
      fontWeightRegular: '500',
      fontWeightBold: '700',
    },
    ui: {
      borderRadiusSmall: '0.125rem',
      borderRadiusMedium: '0.25rem',
      borderRadiusLarge: '0.5rem',
      borderRadiusPill: '0.125rem',
      shadowSoft: '0 0 25px rgba(0, 246, 255, 0.25)',
    },
  },
  midnight: {
    label: 'Midnight',
    colors: {
      background: '#121829',
      surface: '#1a2238',
      surfaceMuted: '#232d4d',
      surfaceElevated: '#2d385d',
      border: '#303c5a',
      ring: '#a78bfa',
      primary: '#8b5cf6',
      primarySoft: '#a78bfa',
      primaryContent: '#ffffff',
      secondary: '#38bdf8',
      secondaryContent: '#0f172a',
      accent: '#f97316',
      accentContent: '#0f172a',
      textPrimary: '#e0e7ff',
      textSecondary: '#94a3b8',
      textMuted: '#64748b',
      success: '#22c55e',
      warning: '#facc15',
      destructive: '#f87171',
      destructiveContent: '#1a2238',
    },
    typography: {
      fontFamilySans: "'Inter', sans-serif",
      fontFamilyDisplay: "'Lexend', sans-serif",
      baseFontSize: '16px',
      fontWeightLight: '300',
      fontWeightRegular: '500',
      fontWeightBold: '700',
    },
    ui: {
      borderRadiusSmall: '0.5rem',
      borderRadiusMedium: '1rem',
      borderRadiusLarge: '1.5rem',
      borderRadiusPill: '9999px',
      shadowSoft: '0 24px 48px -20px rgba(15, 23, 42, 0.55)',
    },
  },
};

module.exports = { themes };
