// Central theme registry for Nest Finance.
// Each theme contains colors, typography, spacing, ui and effect tokens.
// When adding a new theme, keep the structure aligned so the generator and
// ThemeContext can map tokens to CSS variables consistently.

const sharedSpacing = {
  none: '0rem',
  xs: '0.25rem',
  sm: '0.5rem',
  md: '1rem',
  lg: '1.5rem',
  xl: '2rem',
  '2xl': '3rem',
  '3xl': '4rem',
};

const themes = {
  default: {
    label: 'Default',
    colors: {
      background: '#f8fafc',
      surface: '#ffffff',
      surfaceElevated: '#f1f5ff',
      surfaceMuted: '#f1f5f9',
      const themes = {
        default: {
          label: 'Default',
          colors: {
            background: '#f8fafc',
            surface: '#ffffff',
            surfaceMuted: '#f1f5f9',
            surfaceElevated: '#ffffff',
            border: '#e2e8f0',
            ring: '#10b981',
            primary: '#0f766e',
            primarySoft: '#14b8a6',
            primaryContent: '#ffffff',
            secondary: '#1d4ed8',
            secondarySoft: '#60a5fa',
            secondaryContent: '#ffffff',
            accent: '#f97316',
            accentSoft: '#fb923c',
            accentContent: '#0f172a',
            textPrimary: '#0f172a',
            textSecondary: '#334155',
            textMuted: '#64748b',
            success: '#16a34a',
            successSoft: '#86efac',
            warning: '#f59e0b',
            destructive: '#dc2626',
            destructiveContent: '#ffffff',
            inputBorder: '#d1d5db',
            overlayTint: 'rgba(15, 23, 42, 0.04)',
            heroBgStart: '#f0f9ff',
            heroBgEnd: '#ecfeff',
          },
          typography: {
            fontFamilySans: "'Inter', sans-serif",
            fontFamilyDisplay: "'Sora', sans-serif",
            fontFamilyMono: "'Roboto Mono', monospace",
            baseFontSize: '16px',
            fontWeightLight: '300',
            fontWeightRegular: '400',
            fontWeightBold: '600',
            fontSizeH1: '2rem',
            fontSizeH2: '1.5rem',
            fontSizeH3: '1.25rem',
          },
          spacing: {
            xs: '0.25rem',
            sm: '0.5rem',
            md: '1rem',
            lg: '1.5rem',
            xl: '2rem',
          },
          gradients: {
            heroStart: 'linear-gradient(135deg, var(--color-primary-soft), var(--color-accent))',
          },
          shadows: {
            soft: '0 10px 15px -3px rgba(15, 23, 42, 0.12), 0 4px 6px -4px rgba(15, 23, 42, 0.08)',
            heavy: '0 20px 50px rgba(2,6,23,0.4)',
          },
          ui: {
            borderRadiusNone: '0px',
            borderRadiusSmall: '0.375rem',
            borderRadiusMedium: '0.75rem',
            borderRadiusLarge: '1.25rem',
            borderRadiusBox: '1rem',
            borderRadiusPill: '9999px',
          },
        },

        elegant: {
          label: 'Elegant',
          colors: {
            background: '#fdfbf7',
            surface: '#ffffff',
            surfaceMuted: '#f9f6f2',
            surfaceElevated: '#f4ece2',
            border: '#ede7e0',
            ring: '#c08a3e',
            primary: '#8c5a32',
            primarySoft: '#a47246',
            primaryContent: '#fdfbf7',
            secondary: '#5a3d2b',
            secondarySoft: '#8a6a55',
            secondaryContent: '#fdfbf7',
            accent: '#c08a3e',
            accentSoft: '#d4b27a',
            accentContent: '#2d2a26',
            textPrimary: '#2d2a26',
            textSecondary: '#5a534e',
            textMuted: '#8b827b',
            success: '#2f855a',
            warning: '#d97706',
            destructive: '#b91c1c',
            destructiveContent: '#fdfbf7',
            inputBorder: '#e6ded4',
            overlayTint: 'rgba(45, 42, 38, 0.03)',
            heroBgStart: '#fff8f0',
            heroBgEnd: '#fff3e8',
          },
          typography: {
            fontFamilySans: "'Lora', serif",
            fontFamilyDisplay: "'Playfair Display', serif",
            fontFamilyMono: "'Courier New', monospace",
            baseFontSize: '17px',
            fontWeightLight: '300',
            fontWeightRegular: '400',
            fontWeightBold: '700',
          },
          spacing: {
            xs: '0.25rem',
            sm: '0.5rem',
            md: '1.2rem',
            lg: '1.75rem',
            xl: '2.5rem',
          },
          gradients: {
            heroStart: 'linear-gradient(135deg, #fff7ed, #fff1e6)',
          },
          shadows: {
            soft: '0 12px 24px -10px rgba(44, 30, 15, 0.35)',
            heavy: '0 30px 60px rgba(38, 28, 20, 0.45)',
          },
          ui: {
            borderRadiusNone: '0px',
            borderRadiusSmall: '0.25rem',
            borderRadiusMedium: '0.5rem',
            borderRadiusLarge: '1rem',
            borderRadiusBox: '1rem',
            borderRadiusPill: '9999px',
          },
        },

        techno: {
          label: 'Techno',
          colors: {
            background: '#0a0c1f',
            surface: '#111528',
            surfaceMuted: '#1a1f3a',
            surfaceElevated: '#1f2642',
            border: '#2c3454',
            ring: '#00f6ff',
            primary: '#00f6ff',
            primarySoft: '#7dffff',
            primaryContent: '#0a0c1f',
            secondary: '#ff3dff',
            secondarySoft: '#ff8cff',
            secondaryContent: '#0a0c1f',
            accent: '#7c3aed',
            accentSoft: '#a78bfa',
            accentContent: '#0a0c1f',
            textPrimary: '#e0e8ff',
            textSecondary: '#a0b3d8',
            textMuted: '#6b7b9c',
            success: '#22d3ee',
            warning: '#facc15',
            destructive: '#f43f5e',
            destructiveContent: '#0a0c1f',
            inputBorder: '#243047',
            overlayTint: 'rgba(0, 0, 0, 0.25)',
            heroBgStart: '#001022',
            heroBgEnd: '#00183a',
          },
          typography: {
            fontFamilySans: "'Space Grotesk', sans-serif",
            fontFamilyDisplay: "'Orbitron', sans-serif",
            fontFamilyMono: "'VT323', monospace",
            baseFontSize: '15px',
            fontWeightLight: '300',
            fontWeightRegular: '500',
            fontWeightBold: '700',
          },
          spacing: {
            xs: '0.125rem',
            sm: '0.375rem',
            md: '0.9rem',
            lg: '1.2rem',
            xl: '1.75rem',
          },
          gradients: {
            heroStart: 'linear-gradient(135deg, rgba(0,246,255,0.12), rgba(124,58,237,0.08))',
          },
          shadows: {
            soft: '0 0 25px rgba(0, 246, 255, 0.25)',
            heavy: '0 30px 60px rgba(0, 0, 0, 0.6)',
          },
          ui: {
            borderRadiusNone: '0px',
            borderRadiusSmall: '0.125rem',
            borderRadiusMedium: '0.25rem',
            borderRadiusLarge: '0.5rem',
            borderRadiusBox: '0.5rem',
            borderRadiusPill: '0.125rem',
          },
        },

        midnight: {
          label: 'Midnight',
          colors: {
            background: '#121829',
            surface: '#1a2238',
            surfaceMuted: '#232d4d',
            surfaceElevated: '#2d385d',
            border: '#303c5a',
            ring: '#a78bfa',
            primary: '#8b5cf6',
            primarySoft: '#a78bfa',
            primaryContent: '#ffffff',
            secondary: '#38bdf8',
            secondarySoft: '#7dd3fc',
            secondaryContent: '#0f172a',
            accent: '#f97316',
            accentSoft: '#fb923c',
            accentContent: '#0f172a',
            textPrimary: '#e0e7ff',
            textSecondary: '#94a3b8',
            textMuted: '#64748b',
            success: '#22c55e',
            warning: '#facc15',
            destructive: '#f87171',
            destructiveContent: '#1a2238',
            inputBorder: '#374151',
            overlayTint: 'rgba(2,6,23,0.5)',
            heroBgStart: '#0f172a',
            heroBgEnd: '#111827',
          },
          typography: {
            fontFamilySans: "'Inter', sans-serif",
            fontFamilyDisplay: "'Lexend', sans-serif",
            fontFamilyMono: "'Roboto Mono', monospace",
            baseFontSize: '16px',
            fontWeightLight: '300',
            fontWeightRegular: '500',
            fontWeightBold: '700',
          },
          spacing: {
            xs: '0.25rem',
            sm: '0.5rem',
            md: '1rem',
            lg: '1.5rem',
            xl: '2rem',
          },
          gradients: {
            heroStart: 'linear-gradient(135deg, rgba(139,92,246,0.12), rgba(56,189,248,0.08))',
          },
          shadows: {
            soft: '0 24px 48px -20px rgba(15, 23, 42, 0.55)',
            heavy: '0 40px 90px rgba(2,6,23,0.7)',
          },
          ui: {
            borderRadiusNone: '0px',
            borderRadiusSmall: '0.5rem',
            borderRadiusMedium: '1rem',
            borderRadiusLarge: '1.5rem',
            borderRadiusBox: '1.25rem',
            borderRadiusPill: '9999px',
          },
        },
      };

      module.exports = { themes };
      focusOutline: '0 0 0 3px rgba(192, 138, 62, 0.35)',
    },
    effects: {
      glowPrimary: '0 0 28px rgba(192, 138, 62, 0.4)',
      glowSecondary: '0 0 28px rgba(140, 90, 50, 0.28)',
    },
  },
  techno: {
    label: 'Techno',
    colors: {
      background: '#050712',
      surface: '#0f1428',
      surfaceElevated: '#151b34',
      surfaceMuted: '#1a1f3a',
      surfaceSubtle: '#1f264280',
      border: '#293154',
      borderMuted: '#1e2542',
      inputBorder: '#37406a',
      ring: '#00f6ff',
      outline: '#7c3aed',
      primary: '#00f6ff',
      primarySoft: '#5ef0ff',
      primaryContent: '#050712',
      primarySoftContent: '#050712',
      secondary: '#ff3dff',
      secondarySoft: '#ff9dff',
      secondaryContent: '#050712',
      secondarySoftContent: '#1c0320',
      accent: '#7c3aed',
      accentSoft: '#c4a0ff',
      accentContent: '#050712',
      accentSoftContent: '#190033',
      success: '#22d3ee',
      successSoft: '#99f6ff',
      successContent: '#050712',
      successSoftContent: '#05212b',
      warning: '#facc15',
      warningSoft: '#fde68a',
      warningContent: '#1c0f00',
      warningSoftContent: '#422006',
      destructive: '#f43f5e',
      destructiveSoft: '#fda4af',
      destructiveContent: '#050712',
      destructiveSoftContent: '#4c0519',
      textPrimary: '#e0e8ff',
      textSecondary: '#a0b3d8',
      textMuted: '#6b7b9c',
      textOnDark: '#e0e8ff',
      heroBgStart: '#00f6ff',
      heroBgEnd: '#7c3aed',
      heroBgAccent: '#ff3dff',
      overlay: '#0ea5e980',
    },
    typography: {
      fontFamilySans: "'Space Grotesk', sans-serif",
      fontFamilyDisplay: "'Orbitron', sans-serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      baseFontSize: '15px',
      fontSizeSm: '13px',
      fontSizeLg: '17px',
      fontSizeH1: '3.1rem',
      fontSizeH2: '2.3rem',
      fontSizeH3: '1.6rem',
      lineHeightBase: '1.55',
      lineHeightTight: '1.15',
      lineHeightLoose: '1.75',
      lineHeightH1: '1.05',
      letterSpacingCaps: '0.4em',
      fontWeightLight: '300',
      fontWeightRegular: '500',
      fontWeightMedium: '600',
      fontWeightBold: '700',
      fontWeightBlack: '800',
    },
    spacing: { ...sharedSpacing },
    ui: {
      borderRadiusNone: '0px',
      borderRadiusSmall: '0.125rem',
      borderRadiusMedium: '0.25rem',
      borderRadiusLarge: '0.5rem',
      borderRadiusExtraLarge: '0.75rem',
      borderRadiusBox: '0.75rem',
      borderRadiusPill: '9999px',
      borderWidthHairline: '1px',
      borderWidthThick: '3px',
      shadowSoft: '0 0 25px rgba(0, 246, 255, 0.25)',
      shadowStrong: '0 0 45px rgba(124, 58, 237, 0.35)',
      backdropBlur: '18px',
      glassOpacity: '0.78',
      focusOutline: '0 0 0 3px rgba(0, 246, 255, 0.35)',
    },
    effects: {
      glowPrimary: '0 0 32px rgba(0, 246, 255, 0.55)',
      glowSecondary: '0 0 32px rgba(124, 58, 237, 0.45)',
    },
  },
  midnight: {
    label: 'Midnight',
    colors: {
      background: '#0f172a',
      surface: '#1a2238',
      surfaceElevated: '#273152',
      surfaceMuted: '#232d4d',
      surfaceSubtle: '#1a223880',
      border: '#303c5a',
      borderMuted: '#202c45',
      inputBorder: '#3a4a6d',
      ring: '#a78bfa',
      outline: '#38bdf8',
      primary: '#8b5cf6',
      primarySoft: '#c4b5fd',
      primaryContent: '#ffffff',
      primarySoftContent: '#312e81',
      secondary: '#38bdf8',
      secondarySoft: '#93c5fd',
      secondaryContent: '#0f172a',
      secondarySoftContent: '#0b1120',
      accent: '#f97316',
      accentSoft: '#fb923c',
      accentContent: '#111827',
      accentSoftContent: '#1f2937',
      success: '#22c55e',
      successSoft: '#4ade80',
      successContent: '#052e16',
      successSoftContent: '#052e16',
      warning: '#facc15',
      warningSoft: '#fde68a',
      warningContent: '#422006',
      warningSoftContent: '#1f1300',
      destructive: '#f87171',
      destructiveSoft: '#fca5a5',
      destructiveContent: '#450a0a',
      destructiveSoftContent: '#450a0a',
      textPrimary: '#e2e8f0',
      textSecondary: '#94a3b8',
      textMuted: '#64748b',
      textOnDark: '#e2e8f0',
      heroBgStart: '#0ea5e9',
      heroBgEnd: '#8b5cf6',
      heroBgAccent: '#f97316',
      overlay: '#1e293b80',
    },
    typography: {
      fontFamilySans: "'Inter', sans-serif",
      fontFamilyDisplay: "'Lexend', sans-serif",
      fontFamilyMono: "'Fira Code', monospace",
      baseFontSize: '16px',
      fontSizeSm: '14px',
      fontSizeLg: '19px',
      fontSizeH1: '3.2rem',
      fontSizeH2: '2.4rem',
      fontSizeH3: '1.65rem',
      lineHeightBase: '1.6',
      lineHeightTight: '1.2',
      lineHeightLoose: '1.85',
      lineHeightH1: '1.08',
      letterSpacingCaps: '0.32em',
      fontWeightLight: '300',
      fontWeightRegular: '500',
      fontWeightMedium: '600',
      fontWeightBold: '700',
      fontWeightBlack: '800',
    },
    spacing: { ...sharedSpacing },
    ui: {
      borderRadiusNone: '0px',
      borderRadiusSmall: '0.5rem',
      borderRadiusMedium: '1rem',
      borderRadiusLarge: '1.5rem',
      borderRadiusExtraLarge: '2rem',
      borderRadiusBox: '1.25rem',
      borderRadiusPill: '9999px',
      borderWidthHairline: '1px',
      borderWidthThick: '2px',
      shadowSoft: '0 24px 48px -20px rgba(15, 23, 42, 0.55)',
      shadowStrong: '0 35px 80px -30px rgba(15, 23, 42, 0.65)',
      backdropBlur: '20px',
      glassOpacity: '0.82',
      focusOutline: '0 0 0 3px rgba(139, 92, 246, 0.45)',
    },
    effects: {
      glowPrimary: '0 0 32px rgba(139, 92, 246, 0.5)',
      glowSecondary: '0 0 32px rgba(14, 165, 233, 0.45)',
    },
  },
};

module.exports = { themes };
